### ISSUE TITLE
[Bug] Error while trying to train using Luna16 dataset

### ISSUE THREAD

**Issue by ShiroDoMain** [MIAinCS/TiCNet#1]
Hi, I want to train this model on my device using the Luna16 dataset, but I have some problems while training.
The error message is that the nrrd file is missing, but I did not see the relevant operations in the preprocessing script.

My environmental information：
Docker on Windows 11
image: pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime
CPU: i9-13900k
GPU: RTX4090

Traceback:
```bash
USE CUDA: True
[Training configuration]
net MainNet
batch_size 1
epochs 120
epoch_rcnn 65
epoch_save 1
checkpoint None
optimizer SGD
init_lr 0.01
weight_decay 0.0001
out_dir /workspace/results/ticnet/2_fold
train_set_list ['split/2_train.csv']
val_set_list ['split/2_val.csv']
data_dir /workspace/datasets/preprocessed
num_workers 8
[Model configuration]
{'anchors': [[5, 5, 5], [10, 10, 10], [20, 20, 20], [30, 30, 30], [50, 50, 50]],
 'augtype': {'flip': True, 'rotate': True, 'scale': True, 'swap': False},
 'aux_loss': False,
 'bbox_border': 8,
 'blacklist': [],
 'bound_size': 12,
 'box_reg_weight': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
 'crop_size': [128, 128, 128],
 'dec_layers': 6,
 'dim_feedforward': 256,
 'dropout': 0.1,
 'enc_layers': 6,
 'hidden_dim': 64,
 'max_stride': 16,
 'nheads': 8,
 'num_class': 2,
 'num_hard': 3,
 'num_neg': 800,
 'num_queries': 512,
 'pad_value': 170,
 'position_embedding': 'sine',
 'pre_norm': '',
 'r_rand_crop': 0.0,
 'rcnn_crop_size': (7, 7, 7),
 'rcnn_test_nms_overlap_threshold': 0.1,
 'rcnn_test_nms_pre_score_threshold': 0.0,
 'rcnn_train_batch_size': 64,
 'rcnn_train_bg_thresh_high': 0.1,
 'rcnn_train_fg_fraction': 0.5,
 'rcnn_train_fg_thresh_low': 0.5,
 'rcnn_train_nms_overlap_threshold': 0.1,
 'rcnn_train_nms_pre_score_threshold': 0.5,
 'return_intermediate_dec': True,
 'roi_names': ['nodule'],
 'rpn_test_nms_overlap_threshold': 0.1,
 'rpn_test_nms_pre_score_threshold': 0.5,
 'rpn_train_bg_thresh_high': 0.02,
 'rpn_train_fg_thresh_low': 0.5,
 'rpn_train_nms_num': 300,
 'rpn_train_nms_overlap_threshold': 0.1,
 'rpn_train_nms_pre_score_threshold': 0.5,
 'stride': 4,
 'th_neg': 0.02,
 'th_pos_train': 0.5,
 'th_pos_val': 1}
Start_epoch 1, out_dir /workspace/results/ticnet/2_fold
Length of train loader 1058, length of valid loader 128
Total:   0%|                                                                | 0/120 [00:00<?, ?it/s]

Start epoch 1, batch_size 4, lr 0.01, use_rcnn False
[Train 1]:   0%|                                                           | 0/1058 [00:00<?, ?it/s]
Total:   0%|                                                                | 0/120 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/train.py", line 292, in <module>
    main()
  File "/workspace/train.py", line 158, in main
    train(model, train_loader, optimizer, i, train_writer)
  File "/workspace/train.py", line 190, in train
    for j, (input, truth_box, truth_label) in t:
  File "/opt/conda/lib/python3.10/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 302, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/workspace/dataset/bbox_reader.py", line 70, in __getitem__
    imgs = self.load_img(filename)
  File "/workspace/dataset/bbox_reader.py", line 122, in load_img
    img, _ = nrrd.read(os.path.join(self.data_dir, '%s_seg.nrrd' % (path_to_img)))
  File "/opt/conda/lib/python3.10/site-packages/nrrd/reader.py", line 506, in read
    with open(filename, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/datasets/preprocessed/1.3.6.1.4.1.14519.5.2.1.6279.6001.994459772950022352718462251777_seg.nrrd'
```

**Comment by WeebOwO** [comment]
Change the dataset func and load it with numpy. 😄

**Comment by imelolee** [comment]
It seems that you should change the suffix of image into your custom file name.
For npy files please use `np.load` etc.
